### ISSUE TITLE
Putting the client Lab in Laravel public folder

### ISSUE THREAD

**Issue by nwaughachukwuma** [amitavroy/vuespa#3]
Hi @amitavroy is it possible to put the client lab in my Laravel public folder, or can you create a laravel package with the working app which can be installed with composer. The reason is that I want one single application root.

**Comment by amitavroy** [comment]
Yes you can do that by having not the entire app but rather the dist folder. Don't put the entire vue js application folder inside public because those files including the webpack and other files being available in public and available.

Putting the dist folder alone ensures you only have the things in public which are essential for running the application.

**Comment by nwaughachukwuma** [comment]
Thanks for your response @amitavroy. But I cannot find the dist folder in the package. What I have in the client_labs folder are build, config, src and static sub folders. Let me mention that I want to achieve the same thing you did with the private messaging and chat. Hope am not asking an off question?

**Comment by nwaughachukwuma** [comment]
Hi @amitavroy I couldn't find the dist folder in the package. What I have in the client_labs directory are the src, config, build and static sub folders. I want to mention that I am hoping to implement the same things you did with Private Messaging and Chat.
